name: n_pin_board
description: Configurable and easy-to-use cross-platform pin board.
version: 0.0.6+3

homepage: https://github.com/nycm1989/nPinBoard
repository: https://github.com/nycm1989/nPinBoard

topics:
  - pin
  - board
  - cross-platform

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

screenshots:
  - description: 'Loaded image screenshot'
    path: screens/1.png

flutter:
  plugin:
    platforms:
      android:
        package: me.neil.npinboard
        pluginClass: NPinBoard
      ios:
        pluginClass: NPinBoard
      macos:
        pluginClass: NPinBoard
      web:
        pluginClass: NPinBoard
        fileName: n_pin_board.dart
      windows:
        pluginClass: NPinBoardApi

# https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
# dart pub publish --dry-run