name: n_pin_board
description: Configurable and easy-to-use cross-platform pin board.
version: 1.0.2

homepage: https://github.com/nycm1989/nPinBoard
repository: https://github.com/nycm1989/nPinBoard

topics:
  - pin
  - board
  - cross-platform

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'Loaded image screenshot'
    path: screens/1.png

# dart pub publish --dry-run